### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#34]
1. If you have Python 3, you have to do pip3 install .
2. I think graphviz is needed for the graph component. On mac this should be installed through homebrew, so I've read: brew install graphviz. I didn't actually get this to work due to some path problems which I didn't try very hard to fix.
3. Users should run the serializer after onto_tool in order to restore the nice formatting.

**Comment by sa-bpelakh** [comment]
1. I believe `pip` now by default acts as `pip3` (at least that is how I use it). Have you actually run into problems?
2. That is correct, `graphviz` does need to be installed and in the path to generate the PNG. I will add that to the documentation.
3. I think we should build that into the tool. I had at one point of time started to work on providing consistent (sorted) serialization in rdflib to remove the `rdf-toolkit.jar` dependency from `onto_tool`, but that work was put on hold due to lack of bandwidth. I certainly don't want to hardcode the serializer config, which is why the tool configuration in the bundle is very flexible. Some discussion is needed here.

**Comment by rjyounes** [comment]
1. pip doesn't default to pip3 for me, and pip would not install it. That could be a problem with my setup, though.
3. I'm not convinced it's worth it for you to spend time recreating rdf-toolkit - though it does have a few objectionable behaviors. Running it automatically is a good idea.
