### ISSUE TITLE
Write report even on successful completion of migration

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#73]
I'd like to see a report just to know the migration succeeded without any problems.

**Comment by sa-bpelakh** [comment]
What would that entail, exactly? You can attach `message` fields to your build file, so that onto-tool reports the steps as they are executed (eg https://github.com/semanticarts/gist/blob/develop/migration/v10.0/migrate_local.yaml#L16), and if you are really curious, you can smack a `--debug` on the command line and _really_ dive into it. 

But if you are looking for something like 'Updated 32 triples' - we don't have a good way of doing that, especially when the changes are performed on a remote endpoint as opposed to local content. Technically you could write two sets of queries - a SELECT query which reports how many entities it's _going_ to update, followed by the actual UPDATE query that does the job.

**Comment by sa-bpelakh** [comment]
I think the primary point is that migration is not a built-in functionality in onto-tool - it's just a specific utilization of its ability to perform queries and transform RDF.

**Comment by rjyounes** [comment]
OK, I see. I keep forgetting that.
