### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/ontology-toolkit#74]
I'd like to see a report in the report directory just to know the migration succeeded without any problems. Maybe include a summary such as: 

```
Migration completed  with [no|x] issues detected.
Migrated x classes.
Migrated y properties.
N files updated:
  - filename 1
  - filename 2
M files unchanged:
  - filename 3
  - filename4
The following issuesmust be addressed manually:
   - issue 1
   - issue 2
```

You could also add this, or an abbreviated version, on the commandline after execution.

Or a running list in the shell:

```
Migrating <filename>...
No changes to <filename>
....
```

**Comment by bpelakh** [comment]
Since migration is accomplished just by running SPARQL queries, you could technically accomplish this by running a pre-update query to determine what _will_ be migrated, followed by the query to actually do it. The first query could report results. 

Not sure how you would detect and/or report issues encountered.
