### ISSUE TITLE
Smarter data graphic in the presence of superclasses

### ISSUE THREAD

**Issue by sa-bpelakh** [semanticarts/ontology-toolkit#80]
The current rendering of instance data is not class hierarchy-aware, rendering every class -> class relationship as they are asserted. This can lead to misleadingly busy diagrams when entities have more than one `rdf:type` and some of these classes are sub-classes of the others. There are many reasons this can occur - for example a 1st pass ETL can assign a superclass to all instances, and additional classes are then asserted after more information is ingested. Alternately, multiple classes can be attached to an instance due to inference.

Here is a small example ontology to demonstrate the issue:
```
@prefix : <http://example.org/> .

# Classes

:Person a owl:Class .
:Student a owl:Class ;
         rdfs:subClassOf :Person .
:Professor a owl:Class ;
           rdfs:subClassOf :Person .

:Organization a owl:Class .
:Fraternity a owl:Class ;
            rdfs:subClassOf :Organization .
:SocialClub a owl:Class ;
            rdfs:subClassOf :Organization .

:Location a owl:Class .
:SingleFamilyHome a owl:Class ;
                  rdfs:subClassOf :Location .
:Apartment a owl:Class ;
           rdfs:subClassOf :Location .

# Properties

:residesAt a owl:ObjectProperty .
:memberOf a owl:ObjectProperty .
:age a owl:DatatypeProperty .

# Instances

:AloofAcademic
    a :Person, :Professor ;
    :age 50 ;
    :residesAt :ResplendentMansion ;
    :memberOf :TuesdayBookClub .

:TuesdayBookClub a :SocialClub, :Organization .
:ResplendentMansion a :Location, :SingleFamilyHome .

:GrimGradStudent
    a :Student, :Person ;
    :age 25 ;
    :residesAt :CheapHovel ;
    :memberOf :AEP, :Costco .

:AEP a :Organization, :Fraternity .
:CheapHovel a :Location, :Apartment .
:Costco a :Organization .

:Townie
    a :Person ;
    :age 35 ;
    :memberOf :Costco .
```

The current rendering of this ontology (with `--predicate-threshold` set to 0) is:
![image](https://user-images.githubusercontent.com/44446537/136678414-296a0826-a279-415a-a9e3-b255efaf597c.png)
but what we would really want is to have each relationship go only between the most specific classes where it is present, and the datatype property pushed to the lowest-level class for which it is present, as follows:
![image](https://user-images.githubusercontent.com/44446537/136678628-11f0f04d-21fe-4e11-9ba9-5f9471f8ec50.png)
What do you think? How would you render this? Would you include `subClassOf` links between objects such as `SocialClub -> Organization`?

You can regenerate the base diagram using `onto_tool graphic --data -t "Inheritance Confusion" --predicate-threshold 0 --no-image -o confusing confusing_graph.ttl` (which will create a `confusing.dot`), then paste it into [@pwin's Turtle Viewer](http://semantechs.co.uk/turtle-editor-viewer/) and play with it.

**Comment by sa-bpelakh** [comment]
Experimented with modifying the object property query to 
```
                   select ?src ?tgt (COUNT(?src) as ?num) where {
                     {
                        select (group_concat(?src_c) as ?src) (group_concat(?tgt_c) as ?tgt) where {
                          
                          $pattern

                          FILTER(!ISBLANK(?s))
                          ?s a ?src_c .
                          FILTER (!STRSTARTS(STR(?src_c), 'http://www.w3.org/2002/07/owl#'))
                          ?o a ?tgt_c .
                        } group by ?s ?o LIMIT $limit
                      }
                    } group by ?src ?tgt
```
It seems wasteful to continuously re-read class labels, should gather them up-front and do away with the extra level of nesting.

**Comment by uscholdm** [comment]
> Would you include subClassOf links between objects such as SocialClub -> Organization?

Interesting question.  Minimally, include those subclass links such as between Student and Person, since there are direct links from an individual that is an instance of both. On the one hand it would be nice to see some extra and relevant subclass of links - but when exactly to include a subclass link and avoid things getting overly complicated?   If you can think of a suitable criteria, then you could add a 'include all relevant subclasses' option instead of including just the necessary ones.

BTW, I think there should be a link `:Person residesAt  SingleFamilyHome` becaues the Professor is also an explicit instance of   `:Person`.  This is analogous to including the link: `:Student :memberOf :Organization`.

**Comment by sa-bpelakh** [comment]
> Interesting question. Minimally, include those subclass links such as between Student and Person, since there are direct links from an individual that is an instance of both. On the one hand it would be nice to see some extra and relevant subclass of links - but when exactly to include a subclass link and avoid things getting overly complicated? If you can think of a suitable criteria, then you could add a 'include all relevant subclasses' option instead of including just the necessary ones.

The main challenge is how to capture information without making the graph too busy. I am thinking of a command line flag (`--subclass-as`) that toggles how superclass relationships are expressed, one of the following choices:
1. `link` - show it as a different color arrow, as in my example,
2. `node` - show superclasses in the subclass node, like parent classes in a UML diagram, or
3. `none` - omit them entirely, for decluttering

> 
> BTW, I think there should be a link `:Person residesAt SingleFamilyHome` becaues the Professor is also an explicit instance of `:Person`. This is analogous to including the link: `:Student :memberOf :Organization`.

The idea is only to render the most specific class. `:Student :memberOf :Organization` is rendered because `:Costco` is an organization with no other types. Otherwise `:Student` would only have a link to `:Fraternity`

**Comment by uscholdm** [comment]
> node - show superclasses in the subclass node, like parent classes in a UML diagram, 

UML subclass links are arrows. Im not sure what you are thinking that will look different, other than the arrowhead.

**Comment by uscholdm** [comment]
> The idea is only to render the most specific class. `:Student :memberOf :Organization` is rendered because `:Costco` is an organization with no other types. Otherwise `:Student` would only have a link to `:Fraternity`

Oh yes, now I see.

**Comment by uscholdm** [comment]
You asked if there as a way to simplify the output using subclass relationships for the objects of triples. For example could the following be usefully simplified?
 
![image](https://user-images.githubusercontent.com/10777545/136866377-d00a9f4e-4cbf-438a-bbcd-7f59573f4697.png)

Some symbols have specific originating regions that point 
1.	only to instances of Region.
E.g. https://data.platts.com/pleo/_Region_USGulfCoast
2.	to instances of both Region and also CountryRegion, but nothing else
E.g. https://data.platts.com/pleo/_Region_Australia
3.	to instances of Region and also AdministrativeRegion, but nothing else
e.g https://data.platts.com/pleo/_Region_Esmeraldas

For case 1, you will need a link directly from Symbol to Region.
For case 2, you will need a link directly from Symbol to CountryRegion (but not to Region)
For case 3 you will need a link directly from Symbol to AdministartiveRegion (but not to CountryRegion or Region)

So in fact we need to have all three, to cater to the existing triples, which presumably is exactly why the code does this now. That may be why you cannot think of a better diagram. To simplify it means throwing some information away. We can do that, but would have to do so carefully.

One simpler view that throws information out about what direct links there are would be to just point to AdministartiveRegion and have blue arrows connecting that to CountryRegion and from CountryRegion to Region. This would, by convention, mean that some links went directly to the superclasses. These subclass links would ONLY show up when there are direct links to the superclasses.  

It would look like this:

![image](https://user-images.githubusercontent.com/10777545/136866955-737cd168-5f5c-426d-9295-e82113ebff72.png)

In the Platts example in question it would work because there are only two link types that point to the region classes. If there were other links coming from other classes to the region classes, it could get ugly. 

You'd have to do something clever about line thicknesses, if you wanted to know where the direct links were going.  Could we make the thickness of the blue arrows between the regions indicate more links?. 

It occurred to me that here, the subclass links between subjects are separate from the subclass links between objects. That is just an accident. Intermixing them might get ugly and the idea I had might not work.

**Comment by bpelakh** [comment]
Fixed in https://github.com/semanticarts/ontology-toolkit/pull/81
